const q=(question,choices,answer)=>({question,choices,answer});
export const LESSON_QUIZZES={
foundations:[
q("What is the best posture when a Bible passage is difficult to understand?",["Invent a meaning that feels right","Ignore the passage","Say, “I do not understand yet,” and keep investigating","Assume the translation is wrong"],2),
q("Which question keeps Bible study centered on God?",["What does this reveal about God’s character?","How can I win an argument?","How quickly can I finish?","Which detail can I skip?"],0),
q("What should we look for when asking how a passage is redemptive?",["Only a prediction of dates","How God saves, heals, restores, corrects, or gives life","A hidden code in every number","A reason to avoid application"],1),
q("In Romans 1, God’s wrath is described primarily as what?",["God giving people over to the results of their choices","God losing control","A human temper tantrum","Proof that mercy does not matter"],0),
q("What is the relationship between God’s mercy and justice?",["They always contradict each other","Mercy eliminates every consequence","Both belong to God’s loving character","Justice matters but mercy does not"],2),
q("In Bible study, God’s “name” often points to what?",["Only pronunciation","His character","A secret password","A modern denomination"],1),
q("What does it mean for God to be holy?",["He is selfish","He is merely distant","He is completely set apart in goodness and character","He refuses to help sinners"],2),
q("What does sin reveal our need for?",["More self-confidence alone","A Savior and restoration","Less Scripture","A new argument"],1),
q("According to the lesson, God’s law helps reveal what?",["Sin and the character of love","That salvation is earned","That context is unnecessary","That only scholars can read Scripture"],0),
q("What is a central goal of the Foundations lesson?",["To establish helpful ideas and interpretive guardrails","To memorize every Bible book in one day","To replace Scripture with opinions","To make every passage symbolic"],0)],
"look-for-christ":[
q("What central question guides this method?",["How long is the chapter?","Where is Christ in this passage?","Who printed this Bible?","How many verses can I skip?"],1),
q("What did Jesus explain on the road to Emmaus?",["Only Roman history","What the Scriptures said concerning Himself","How to avoid the Old Testament","Why questions are unnecessary"],1),
q("How should a possible Christ connection be tested?",["By whether it sounds creative","By context and the wider message of Scripture","By social media popularity","By ignoring the author’s meaning"],1),
q("What should the student avoid?",["Reading related passages","Praying before studying","Forcing a symbolic connection the text does not support","Looking at the whole story"],2),
q("Rahab’s scarlet cord can invite reflection on what theme?",["Rescue and deliverance","Agricultural law only","The value of wealth","Roman citizenship"],0),
q("Looking for Christ includes noticing what?",["His character, work, mission, sacrifice, and teachings","Only His name printed explicitly","Only New Testament geography","Only miracles"],0),
q("Why compare related Bible passages?",["To let Scripture help clarify Scripture","To avoid reading the passage itself","To guarantee every detail is symbolic","To replace prayer"],0),
q("What does asking “Where am I?” encourage?",["Personal reflection and response","Changing the biblical location","Ignoring God’s character","Finding your name in the text"],0),
q("A faithful Christ-centered reading should first respect what?",["The passage’s context and meaning","The newest interpretation online","A clever analogy","The shortest possible answer"],0),
q("What is the purpose of finding Christ throughout Scripture?",["To draw people toward Jesus and the gospel","To erase the original story","To avoid practical application","To make every character Jesus"],0)],
"pattern-recognition":[
q("What is the first practical step in pattern recognition?",["Break the passage into its main steps or movements","Choose a conclusion before reading","Search only for repeated numbers","Skip unfamiliar details"],0),
q("What is a biblical pattern?",["A repeated sequence, image, theme, or experience","Any coincidence we imagine","A decorative page border","A list of chapter numbers"],0),
q("Which two passages are compared in the lesson’s main example?",["Isaiah 6 and Luke 5","Genesis 1 and Revelation 22 only","Psalm 23 and Acts 2","Matthew 1 and Romans 16"],0),
q("What comes after noticing a similar sequence in two passages?",["Ask what the repeated pattern teaches","Declare every detail identical","Stop reading the context","Remove the differences"],0),
q("Why should the steps be written in order?",["To see the movement and sequence clearly","To change the story","To make the passage shorter","To avoid cross-references"],0),
q("What can repeated Bible patterns reveal?",["How God acts and how people respond","A guaranteed date for every event","That every passage has the same genre","That context is optional"],0),
q("How should a proposed pattern be checked?",["Against context and other Scripture","Only by personal feelings","By how surprising it sounds","By ignoring differences"],0),
q("What is a danger in pattern recognition?",["Forcing similarities that the text does not support","Reading a passage twice","Writing down the sequence","Comparing Scripture with Scripture"],0),
q("Why note both similarities and differences?",["To keep the comparison accurate","To prove the passages are identical","To avoid interpretation","To remove the original meaning"],0),
q("What is the final goal of recognizing a pattern?",["To understand and apply biblical truth more clearly","To impress people with hidden codes","To replace exegesis","To avoid Christ-centered study"],0)],
"questioning-method":[
q("Which six words form the Questioning Method?",["Read, repeat, recite, record, review, respond","Who, what, when, where, why, and how","Past, present, future, law, grace, glory","Start, stop, wait, watch, listen, speak"],1),
q("What does the “Who?” question investigate?",["People, groups, speakers, and listeners","Only the author’s age","The weather","Chapter length"],0),
q("What does the “What?” question investigate?",["Events, words, actions, commands, and conflicts","Only locations","Only dates","Only names"],0),
q("Why ask “When?”",["To notice timing, sequence, and what happens before or after","To predict every future date","To avoid historical context","To count punctuation"],0),
q("What does the “Where?” question explore?",["Place, geography, setting, and their significance","Only the reader’s location","The page number","The publisher’s address"],0),
q("What does asking “Why?” help uncover?",["Motives, reasons, causes, and purpose","Only word definitions","The number of characters","The Bible’s print date"],0),
q("What does the “How?” question examine?",["Method, development, response, and outcome","Only the ending","Only grammar","Only symbolism"],0),
q("Why are open-ended questions valuable?",["They invite observation, thought, and investigation","They guarantee one-word answers","They eliminate the need to read","They make context irrelevant"],0),
q("What should questions arise from?",["Details actually present in the passage","A conclusion chosen beforehand","Unrelated opinions","A desire to confuse others"],0),
q("What is the main benefit of the Questioning Method?",["It turns curiosity into deeper Bible investigation","It replaces Scripture with a checklist","It prevents personal application","It makes every answer immediate"],0)],
exegesis:[
q("What is exegesis?",["Drawing the intended meaning out of the text","Reading our ideas into the text","Skipping difficult verses","Treating every passage as poetry"],0),
q("What is eisegesis?",["Studying historical context","Reading our own ideas into Scripture","Comparing translations","Finding cross-references"],1),
q("What does historical context ask?",["Who wrote it, to whom, when, and what was happening","Which verse is shortest","How popular the passage is","What the reader already believes"],0),
q("What does literary context include?",["What comes before and after and the passage’s genre","Only the chapter heading","Only modern application","The color of the Bible cover"],0),
q("Why does genre matter?",["Poetry, history, prophecy, parable, and other forms communicate differently","Every genre must be read identically","Genre replaces context","Genre determines the Bible translation"],0),
q("What is authorial intent?",["What the writer intended to communicate to the original audience","Whatever a modern reader prefers","A hidden meaning unrelated to the passage","Only the author’s biography"],0),
q("How can cross-references help?",["Other Scriptures can clarify the passage","They make the immediate context unnecessary","They prove every analogy","They replace careful reading"],0),
q("When should personal application come?",["After understanding what the text says and means","Before reading the passage","Instead of interpretation","Only after memorizing the whole Bible"],0),
q("What should a careful interpreter be willing to say?",["I do not understand yet","My first thought must be correct","Context never changes anything","Every detail is symbolic"],0),
q("Which practice best protects against eisegesis?",["Checking context, genre, words, cross-references, and authorial intent","Choosing a meaning before reading","Using one isolated phrase","Ignoring the original audience"],0)],
"bible-memorization":[
q("Why memorize Scripture?",["To keep God’s Word available in the mind and heart","To avoid understanding it","To impress others only","To replace reading the Bible"],0),
q("Which basic practice strengthens memory?",["Repetition over time","Reading once very quickly","Avoiding review","Changing the words each time"],0),
q("What does the word-emphasis method involve?",["Repeating the verse while stressing a different word","Removing difficult words","Reading only the first word","Alphabetizing the verse"],0),
q("Why say a passage aloud?",["Hearing and speaking add more pathways for recall","It changes the passage’s meaning","It removes the need for review","It guarantees instant mastery"],0),
q("What is useful after reading the verse several times?",["Test yourself without looking","Immediately choose a new verse","Stop before recalling it","Rewrite it in different words only"],0),
q("What is a chapter-topic method?",["Linking a chapter with its main subject or theme","Memorizing only chapter numbers","Ignoring the passage’s subject","Reading chapters randomly"],0),
q("How can Scripture songs help?",["Melody and rhythm can strengthen recall","They replace the biblical words","They eliminate repetition","They work only for children"],0),
q("Which review schedule is most helpful?",["Review today, tomorrow, and again later","Review once and never return","Wait until the verse is forgotten","Study only once a year"],0),
q("What should you do when you miss a word?",["Check the verse, correct it, and repeat it accurately","Invent a replacement","Give up permanently","Skip the rest of the passage"],0),
q("What makes memorization spiritually useful?",["Understanding, reflecting on, and living the truth remembered","Reciting without meaning","Competing for the longest list","Avoiding application"],0)],
"word-search":[
q("What is the purpose of the Word Search Method?",["To investigate how an important biblical word is used and understood","To find decorative fonts","To replace reading the passage","To count every word in the Bible"],0),
q("What tool lists where a Bible word appears?",["A concordance","A calendar","A hymnal index only","A map legend"],0),
q("What does a Strong’s number help identify?",["The underlying Hebrew or Greek word","The verse’s reading level","The author’s age","A modern page number"],0),
q("Why examine the original Hebrew or Greek word?",["It can clarify meaning and usage","It makes context unnecessary","It guarantees a secret meaning","It replaces the Bible"],0),
q("What should guide a word’s meaning most strongly?",["Its context and biblical usage","The first English definition online","Personal preference","How unusual the meaning sounds"],0),
q("Why compare several occurrences of the same word?",["To see its range and repeated biblical usage","To assume it means exactly the same thing everywhere","To avoid the immediate passage","To create a hidden code"],0),
q("What is a lexicon?",["A reference that explains words in their original language","A list of Bible maps","A sermon outline","A book of modern quotations"],0),
q("What mistake should a word study avoid?",["Importing every possible dictionary meaning into one verse","Checking cross-references","Reading the paragraph","Noting repeated words"],0),
q("How can Blue Letter Bible assist this method?",["It provides concordance, Strong’s, and original-language tools","It writes the final interpretation automatically","It removes the need for Scripture","It limits study to one translation"],0),
q("What should a completed word study explain?",["What the word means in this passage and why it matters","Every meaning the word has ever had","Only how the word sounds","Why context can be ignored"],0)]};
